[tool.isort]
line_length = 119
profile = "black"
py_version = 312
force_to_top = ["app.ml.models.ml_model"]  # This import should be on top to avoid circular import in "app.ml.models"

[tool.black]
line-length = 119
target-version = ["py312"]

[tool.pytest.ini_options]
minversion = "6.0"
required_plugins = "pytest-cov"
testpaths = ["test"]
